name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.type }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  validate-build:
    runs-on: [ ubuntu-latest ]
    uses: ./.github/workflows/validate-build-client.yml
      secrets: inherit
