name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  BRANCH: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'  && 'main' || github.head_ref }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.type }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  export-variables:
    runs-on: [ ubuntu-latest ]
    outputs:
      BRANCH: ${{ env.BRANCH }}

    steps:
      - name: Exporting variables
        run: echo exporting environment variables to be used in reusable jobs.

  validate-build-client:
    needs: [ export-variables ]
    uses: ./.github/workflows/validate-build-client.yml
    secrets: inherit
    with:
      branch: ${{ needs.export-variables.outputs.BRANCH }}

