name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.type }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-build:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout latest code for the ref ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
          persist-credentials: false

      - name: Build Client
        uses: ./.github/workflows/validate-build-client.yml

