name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.type }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-build:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Build Client
        uses: ./.github/workflows/validate-build-client.yml
        with:
          inherit: secrets
