name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.type }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkout-code:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout latest code for the ref ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
          persist-credentials: false

      - name: Get Branch Name
        run: |
          pwd
          ls -l .github/workflows
          if [ "${GITHUB_REF_NAME}" != main ]; then # Pull Request
            export BRANCH="${GITHUB_HEAD_REF}"
          else # merge request commit
            export BRANCH="main"
          fi
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
  
  validate-build:
    needs: [ checkout-code ]
    uses: ./.github/workflows/validate-build-client.yml
    secrets: inherit
    with:
      branch: ${{ GITHUB_ENV.BRANCH }}

