name: validate-build
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string


env:
  BRANCH: ${{ inputs.branch }}

jobs:
  validate-and-build:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout latest code for the ref ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
          persist-credentials: false
          
      - name: Initialize SDK for Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Run maven clean build and package
        run: |
          ./mvnw -Dbranch_version=$BRANCH clean verify package

      - name: Verify the build
        run: |
          ls -l target
          java -jar target/email-notification-$BRANCH.jar --input data/email1.mustache --data data/data.json --output data/out.json
